package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComOllvenSubmodulesRefsHeadsMain'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComOllvenSubmodulesRefsHeadsMain")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComOllvenSubmodulesRefsHeadsMain")
        name = "https://github.com/ollven/Submodules#refs/heads/main"
        url = "https://github.com/ollven/Submodules"
        branch = "refs/heads/main"
        branchSpec = "refs/heads/*"
        checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.NON_RECURSIVE_CHECKOUT
        userForTags = "ollven<ollven@yandex.ru>"
        authMethod = password {
            userName = "ollven"
            password = "credentialsJSON:9fd10c2d-c48f-40aa-9156-19acfe23cab2"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.SUBMODULES_CHECKOUT
    }

}
